services:

  localstack:
    image: localstack/localstack:3.4
    container_name: localstack

    ports:
      - "4566:4566"

    environment:
      - SERVICES=dynamodb,sqs

    volumes:
      - "./localstack/init:/etc/localstack/init/ready.d"

  classreview-api:
    build:
      context: .
      dockerfile: src/main/docker/Dockerfile.jvm

    container_name: classreview-api

    ports:
      - "8081:8080"

    depends_on:
      - localstack

    environment:
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
      - AWS_REGION=us-east-1