AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Resources:

  FeedbackFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: io.quarkus.amazon.lambda.runtime.QuarkusStreamHandler::handleRequest
      Runtime: java21
      CodeUri: target/function.zip

      MemorySize: 512
      Timeout: 30

      Policies:
        - DynamoDBCrudPolicy:
            TableName: Feedback

        - SQSPollerPolicy:
            QueueName: critical-feedback

        - Statement:
            - Effect: Allow
              Action:
                - sqs:SendMessage
              Resource: !GetAtt CriticalFeedbackQueue.Arn


      Events:
        CreateFeedback:
          Type: Api
          Properties:
            Path: /feedbacks
            Method: POST

      Environment:
        Variables:
          QUARKUS_DYNAMODB_AWS_REGION: us-east-1
          QUARKUS_SQS_AWS_REGION: us-east-1

  FeedbackTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: Feedback
      BillingMode: PAY_PER_REQUEST

      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S

      KeySchema:
        - AttributeName: id
          KeyType: HASH

  CriticalFeedbackQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: critical-feedback

Outputs:

  ApiUrl:
    Description: HTTP API endpoint URL
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/feedbacks"