%test.quarkus.http.port=8081
%test.quarkus.scheduler.enabled=false

quarkus.dynamodb.aws.credentials.type=static
quarkus.dynamodb.aws.credentials.static-provider.access-key-id=test
quarkus.dynamodb.aws.credentials.static-provider.secret-access-key=test

%test.quarkus.dynamodb.endpoint-override=http://localhost:4566
%test.quarkus.dynamodb.aws.region=us-east-1

%test.quarkus.sqs.endpoint-override=http://localhost:4566
%test.quarkus.sqs.aws.region=us-east-1

%test.quarkus.sqs.aws.credentials.type=static
%test.quarkus.sqs.aws.credentials.static-provider.access-key-id=test
%test.quarkus.sqs.aws.credentials.static-provider.secret-access-key=test

%test.critical-feedback.queue.url=http://localhost:4566/000000000000/critical-feedback

critical-feedback.queue.url=http://localhost:4566/000000000000/critical-feedback

quarkus.http.port=8081

quarkus.dynamodb.endpoint-override=http://localhost:4566
quarkus.dynamodb.aws.region=us-east-1

quarkus.sqs.endpoint-override=http://localhost:4566
quarkus.sqs.aws.region=us-east-1

quarkus.sqs.aws.credentials.type=static
quarkus.sqs.aws.credentials.static-provider.access-key-id=test
quarkus.sqs.aws.credentials.static-provider.secret-access-key=test