
quarkus.http.port=8081
# Credenciais fake
quarkus.aws.credentials.type=static
quarkus.aws.credentials.static-provider.access-key-id=test
quarkus.aws.credentials.static-provider.secret-access-key=test

# DynamoDB
quarkus.dynamodb.endpoint-override=http://localhost:4566
quarkus.dynamodb.aws.region=us-east-1

# SQS
quarkus.sqs.endpoint-override=http://localhost:4566
quarkus.sqs.aws.region=us-east-1

quarkus.sqs.aws.credentials.type=static
quarkus.sqs.aws.credentials.static-provider.access-key-id=test
quarkus.sqs.aws.credentials.static-provider.secret-access-key=test

# Queue
critical-feedback.queue.url=http://sqs.us-east-1.localhost.localstack.cloud:4566/000000000000/critical-feedback

quarkus.swagger-ui.always-include=true