%test.quarkus.http.port=8081
%test.quarkus.scheduler.enabled=false

# =========================
# TEST / LOCALSTACK
# =========================

%test.quarkus.dynamodb.endpoint-override=http://localhost:4566
%test.quarkus.dynamodb.aws.region=us-east-1
%test.quarkus.dynamodb.aws.credentials.type=static
%test.quarkus.dynamodb.aws.credentials.static-provider.access-key-id=test
%test.quarkus.dynamodb.aws.credentials.static-provider.secret-access-key=test

%test.quarkus.sqs.endpoint-override=http://localhost:4566
%test.quarkus.sqs.aws.region=us-east-1
%test.quarkus.sqs.aws.credentials.type=static
%test.quarkus.sqs.aws.credentials.static-provider.access-key-id=test
%test.quarkus.sqs.aws.credentials.static-provider.secret-access-key=test

%test.critical-feedback.queue.url=http://localhost:4566/000000000000/critical-feedback

# =========================
# DEV
# =========================

%dev.quarkus.http.port=8081
%dev.quarkus.http.host=0.0.0.0

%dev.quarkus.dynamodb.endpoint-override=http://localhost:4566
%dev.quarkus.dynamodb.aws.region=us-east-1
%dev.quarkus.dynamodb.aws.credentials.type=static
%dev.quarkus.dynamodb.aws.credentials.static-provider.access-key-id=test
%dev.quarkus.dynamodb.aws.credentials.static-provider.secret-access-key=test

%dev.quarkus.sqs.endpoint-override=http://localhost:4566
%dev.quarkus.sqs.aws.region=us-east-1
%dev.quarkus.sqs.aws.credentials.type=static
%dev.quarkus.sqs.aws.credentials.static-provider.access-key-id=test
%dev.quarkus.sqs.aws.credentials.static-provider.secret-access-key=test

%dev.critical-feedback.queue.url=http://localhost:4566/000000000000/critical-feedback

# =========================
# PROD / AWS
# =========================

quarkus.dynamodb.aws.region=us-east-1
quarkus.sqs.aws.region=us-east-1

critical-feedback.queue.url=https://sqs.us-east-1.amazonaws.com/112920803674/critical-feedback

quarkus.lambda.mock-event-server.dev-port=0